spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: springcloud-provider-dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

server:
  port: 8001
---
spring:
  profiles: test
  application:
    name: springcloud-provider-test
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
server:
  port: 8002
