spring: 
  profiles:
    active: dev

---
server:
  port: 8003
#spring配置
spring:
  profiles: dev
  application:
    name: springcloud-provider
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---
server:
  port: 8002
#spring配置
spring:
  profiles: test
  application:
    name: springcloud-provider
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/


