spring:
  profiles:
    active: dev

---
server:
  port: 8001


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #日志
    map-underscore-to-camel-case: true

#spring配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/db01?characterEncoding=utf8&useTimezone=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    fetch-registry: true
  instance:
    instance-id: springcloud-dept-provide-8001  #修改eureka默认描述信息

---
server:
  port: 8001


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #日志
    map-underscore-to-camel-case: true

#spring配置
spring:
  profiles: test
  application:
    name: springcloud-provider-dept
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/db02?characterEncoding=utf8&useTimezone=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    fetch-registry: true
  instance:
    instance-id: springcloud-dept-provide-8001  #修改eureka默认描述信息
