spring:
  profiles:
    active: dev

---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: springcloud-config-eureka

eureka:
  instance:
    hostname: eureka7001.com   #服务端的实例名称
  client:
    fetch-registry: false    #如果为false  则表示为注册中心
    register-with-eureka: false #表示是否向eureka中注册自己
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
server:
  port: 7002

spring:
  profiles: test
  application:
    name: springcloud-provider-dept

eureka:
  instance:
    hostname: eureka7002.com   #服务端的实例名称
  client:
    fetch-registry: false    #如果为false  则表示为注册中心
    register-with-eureka: false #表示是否向eureka中注册自己
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
